version: '3.4'

services:
  mydotnetapp:
    image: mydotnetapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.76.14;Database=W6StockCount;User Id=stock_user;Password=w6stock123#;

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=w6stock123#
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
